services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - cache:/data

  db:
    image: mysql:8
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: distribution
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  webserver:
    volumes:
      - ./php:/var/www/html
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: always
    depends_on:
      - db

volumes:
  db_data:
  cache:
    driver: local